### PR TITLE
#43 add section Inactive Chapters to Guides page

### PR DESCRIPTION
**Pull request by nycuma**
* modified ChapterSection: added new props for title and Booleans to show/hide active or inactive chapters
* added some text and a list with inactive chapters to Guides page

### CODE REVIEW

**Comment by Twissi** [comment]
@nycuma can you please update the copy `OpenTechSchool can provide you with a list of previous chapters and contacts.` to say `See a list of previous chapters at the bottom of the page` or similar :)

**Comment by Twissi** [comment]
One more thing i noticed. Unfortunately we need to remove the links for now, because the pages don't exist yet.

**Comment by nycuma** [comment]
@Twissi I made only one commit today but I think I messed up the PR because I did something wrong with rebasing / merging from master 😭

**Comment by gsambrotta** [comment]
@nycuma you can rebase to master. 
If is a problem i can do that for you :)

**Comment by nycuma** [comment]
I didn't resolve the merge conflicts correctly.. I'll add a new commit in a minute ^^

**Comment by nycuma** [comment]
@gsambrotta Fixed a small error and rebased the branch. Looks fine to me now 😃

**Pull request merged**
