### PR TITLE
Optimize Web Fonts

### PR DESCRIPTION
**Pull request by xMartin**
Let's try to load only what we need in the most efficient way for better loading performance.

### CODE REVIEW

**Comment by xMartin** [comment]
@Twissi Could you check the font weights in the CSS and make sure that it matches the fonts being loaded? Roboto 300 and 500 and OpenSans 300 and 800 don't seem to be used. And OpenSans 500 is being used but not loaded.

**Comment by Twissi** [comment]
I see 
Open Sans: 
- `700` (bold) for h2 and h3 headlines
- `500` for gray headlines
Roboto:
-  `700` (bold) for links
- `400` for regular text

So yes, i think we can remove Roboto 300 and 500 and OpenSans 300 and 800

**Comment by xMartin** [comment]
Roboto:400,~500~,700, right?

**Comment by xMartin** [comment]
@Twissi  We have `b, strong { font-weight: bold; font-weight: 500; }`. Do we want 500 for all bold in primary font? Should we add 500 to `a`s? Why do we have `bold` *and* `500`?

**Comment by Twissi** [comment]
I was thinking bold === 500

**Pull request merged**
