### PR TITLE
learners members link meetup

### PR DESCRIPTION
**Pull request by gsambrotta**
Screen Shot 2020-04-15 at 12 25 52
Members numbers is a link to meetup page now.

### CODE REVIEW

**Comment by xMartin** [comment]
I don't think it's great UX. As a user I wouldn't know what to expect when I click on that.

How might we explain that this number is actually meetup.com members and let the user become one, too?

**Comment by Twissi** [comment]
Noticed the Team members are suddenly missing. Seems fine in master, not sure it's related to this PR.

**Comment by Twissi** [comment]
Looks like we don't have a `Join on Meetup` CTA on the page, so we can just add that back

**Comment by gsambrotta** [comment]
> Looks like we don't have a `Join on Meetup` CTA on the page, so we can just add that back

we had a discussion on slack about this: https://opentechschool.slack.com/archives/C04KVFEKY/p1586623939044000

I'm a bit against putting a cta link for meetup.
I would like we discuss it before we put it there. A cta button is a big deal in term of communication, we should think it trough properly.

**Comment by gsambrotta** [comment]
> I don't think it's great UX. As a user I wouldn't know what to expect when I click on that.
> 
> How might we explain that this number is actually meetup.com members and let the user become one, too?

We can just add: 
`n. learners already joined on meetup.com` 
or
`n. learners on meetup.com -> join us as well`
We have space so we can be verbose.

**Comment by gsambrotta** [comment]
@xMartin @Twissi , any input?

**Comment by Twissi** [comment]
> n. learners on meetup.com

sounds good to me for now

**Pull request merged**
