### PR TITLE
2020 version...

### PR DESCRIPTION
**Pull request by aoloe**

### CODE REVIEW

**Comment by Twissi** [comment]
@aoloe thanks for updating your profile.

On the page i am see these missing:
- [ ] header picture and credits
- [ ] second picture
- [ ] organiser picture
- [ ] twitter account

Let me know if you want to provide any of these. 
I think we can hide the twitter timeline if an account is not set and for the pictures maybe have some fallback.

**Comment by aoloe** [comment]
hi @Twissi 

can you  please provide an example for:

- header picture and credits
- second picture
- organizer picture

i couldn't find any chapter having already defined them (i mostly based my description on the ones from berlin and leipzig...)

... and we are not on twitter... sorry.
but i would love to be able to add links to our events pulished on openki and gettogether...

plase tell me if you plan to merge this PR as is (and i should wait for a merge and then create a new  branch) or if you wait for the missing information before merging (and i should make further commits in this PR)

**Comment by Twissi** [comment]
Hi @aoloe 
- header picture: in the `public` folder add a image `zurich_cityBg.jpg` (shows up in the header of your city page)
- credits: add `credits:` to the markdown file, if you need to add image credits (shows up in the header of your city page on top of the image)
- second picture: in the `public` folder add a image `zurich_cityAbout.jpg` (shows up in the about page of the city page)
- organizer picture: in the `public/members` folder add an image `ale.jpg` (shows up in the organizers section of the city page)

You can preview your page here: https://websitenext-p5no5sxoo.now.sh/en/city/zurich

> .. and we are not on twitter... sorry.
no problem at all, i'll remove the twitter feed if not specified

> but i would love to be able to add links to our events pulished on openki and gettogether...
can you add the links in the markdown file or is this not what you are looking for?

> plase tell me if you plan to merge this PR as is (and i should wait for a merge and then create a new branch) or if you wait for the missing information before merging (and i should make further commits in this PR)
let me know if you will be able to update the missing images otherwise i think we can also merge what you have so far.

**Comment by aoloe** [comment]
- i've added the zurich pictures. if you need a different ratio, for the Bg one, there is also an "uncut" version: <https://opentechschool-zurich.github.io/assets/posts/2018-10-09.jpg>
- my portrait is the one that is currently on the ots site....
- social icons: yes, it would be nice, to have  icons and links for other services on top of the few big and not open ones.
- concerning the credits: the picture of mine has been "stolen" from the internet by robert. so no credits. the other pictures are by myself and since there are people in there, they cannot be used for goals other than promoting OTS zurich on the website. (they are snapshots so copyrights do not really make sense; free licenses do not apply since using the pictures in different contexts would break the agreement made with the participants ("model release"). it's up to you how to display this. leaving it completely blank is probably fine.)

**Comment by Twissi** [comment]
@aoloe 
thank you for the pictures!

I put in some fixes and it looks great now (pictures work) and twitter, credits are hidden 🎉 
https://websitenext-6h0w1vlcv.now.sh/en/city/zurich

I think we can merge this PR!

> social icons: yes, it would be nice, to have icons and links for other services on top of the few big and not open ones.
can you please add an issue in github explaining which platfoms are missing and where to find them (links). I personally haven't heard of matrix, openki and gettogehter.

**Pull request merged**
